app:
  email:
    verification:
      enabled: true
      expiration-minutes: 30
    sender: ryftaxi@gmail.com
    base-url: http://192.168.5.192:8080
jwt:
  expiration-ms: 86400000
  issuer: ryftaxi-app
  secret-key: mySuperSecretKeyForJWTGenerationInSpringBootApplication2025ThatShouldBeVeryLongAndSecure
ryftaxi:
  openapi:
    dev-url: http://192.168.5.192:8080
    prod-url: https://ryftaxi-production.com
server:
  address: 0.0.0.0
  port: 8080
spring:
  application:
    name: ryftaxi
  banner:
    enabled: true
    location: classpath:banner.txt
  cache:
    caffeine:
      spec: maximumSize=500, expireAfterWrite=60s
    cache-names: userProfileCache
    type: caffeine
  datasource:
    url: jdbc:mysql://localhost:3306/ryftaxi?useSSL=false&serverTimezone=UTC
    username: root
    password: Clave2025
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ryftaxi@gmail.com
    password: byhj frki gkcj wpli
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  web:
    resources:
      static-locations: classpath:/static/
  webflux:
    base-path: /
  websocket:
    allowed-origins: "*"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    validator-url:
  packages-to-scan: com.ryfsystems.ryftaxi.dto, com.ryfsystems.ryftaxi.controller
  paths-to-match: /api/**
  model-and-view-allowed: true

logging:
  level:
    org.springframework.web: DEBUG
