jwt:
  expiration-ms: 86400000
  issuer: ryftaxi-app
  secret-key: mySuperSecretKeyForJWTGenerationInSpringBootApplication2025ThatShouldBeVeryLongAndSecure
server:
  address: 0.0.0.0
  port: 8080
spring:
  application:
    name: ryftaxi
  datasource:
    url: jdbc:mysql://localhost:3306/ryftaxi?useSSL=false&serverTimezone=UTC
    username: root
    password: Clave2025
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  web:
    resources:
      static-locations: classpath:/static/
  webflux:
    base-path: /
  websocket:
    allowed-origins: "*"

logging:
  level:
    org.springframework.web: DEBUG
